/* ====================================================================
   KATALOG PRODUK — satu tempat untuk semua data produk yang bisa dibeli.
   ====================================================================
   Cara nambah produk baru: copy salah satu blok { ... } di bawah,
   ganti isinya, kasih "id" yang unik (huruf kecil, tanpa spasi).

   Field "priceIsEstimate: true" artinya harga yang tampil adalah
   estimasi/harga promo terbatas — harga final tetap dikonfirmasi
   admin lewat WhatsApp saat checkout (jadi aman, gak akan salah kasih
   harga pasti ke customer untuk produk yang harganya bisa berubah).

   Struktur ini sengaja dipisah dari logic (js/cart.js) dan tampilan
   (index.html) supaya gampang nanti kalau mau disambungkan ke
   database/backend asli — tinggal ganti PRODUCTS ini jadi hasil
   fetch() dari API, sisanya (cart, checkout, hitung total) gak perlu
   diubah sama sekali.
   ==================================================================== */
const PRODUCTS = [
  {
    image: "assets/img/produk-epson-eb-e600.jpg",
    id: "eb-e600",
    brand: "Epson",
    name: "Epson EB-E600",
    category: "Proyektor",
    specLine: "XGA · 3.400 Lumens",
    ports: "HDMI | VGA In/Out, No Zoom In/Out",
    price: 5400000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-x600.jpg",
    id: "eb-x600",
    brand: "Epson",
    name: "Epson EB-X600",
    category: "Proyektor",
    specLine: "XGA · 3.600 Lumens",
    ports: "USB | HDMI | VGA In/Out",
    price: 5800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-w55.jpg",
    id: "eb-w55",
    brand: "Epson",
    name: "Epson EB-W55",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Dual HDMI | USB | WiFi",
    price: 8500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-x52.jpg",
    id: "eb-x52",
    brand: "Epson",
    name: "Epson EB-X52",
    category: "Proyektor",
    specLine: "XGA · 3.800 Lumens",
    ports: "USB | Dual HDMI",
    price: 6600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-w53.jpg",
    id: "eb-w53",
    brand: "Epson",
    name: "Epson EB-W53",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "HDMI, No Zoom In/Out",
    price: 7200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-fh54.jpg",
    id: "eb-fh54",
    brand: "Epson",
    name: "Epson EB-FH54",
    category: "Proyektor",
    specLine: "Full HD · 4.100 Lumens",
    ports: "USB | Dual HDMI | WiFi",
    price: 13250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-infocus-in0004sl.jpg",
    id: "infocus-in0004sl",
    brand: "InFocus",
    name: "InFocus IN0004SL",
    category: "Proyektor",
    specLine: "XGA · 4.000 Lumens",
    ports: "HDMI | VGA",
    price: 4900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-spc-p100.jpg",
    id: "spc-p100",
    brand: "SPC",
    name: "SPC P100",
    category: "Proyektor",
    specLine: "XGA · 4.200 Lumens",
    ports: "HDMI | VGA · Bersertifikat TKDN",
    price: 3900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-2065.jpg",
    id: "eb-2065",
    brand: "Epson",
    name: "Epson EB-2065",
    category: "Proyektor",
    specLine: "XGA · 5.500 Lumens",
    ports: "HDMI | USB | LAN",
    price: 21000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-2155w.jpg",
    id: "eb-2155w",
    brand: "Epson",
    name: "Epson EB-2155W",
    category: "Proyektor",
    specLine: "WXGA · 5.000 Lumens",
    ports: "HDMI | USB | LAN",
    price: 23000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-2265u.jpg",
    id: "eb-2265u",
    brand: "Epson",
    name: "Epson EB-2265U",
    category: "Proyektor",
    specLine: "WUXGA · 5.500 Lumens",
    ports: "HDMI | USB | LAN",
    price: 31000000,
    priceIsEstimate: true,
    icon: "projector"
  },

  /* ====================================================================
     PRODUK TAMBAHAN — dari PRICELIST_WEB.xlsx (54 item, semua Epson).
     Foto sudah lengkap untuk semua produk di batch ini.
     ==================================================================== */
  {
    image: "assets/img/produk-eb-e01.jpg",
    id: "eb-e01",
    brand: "Epson",
    name: "Epson EB-E01",
    category: "Proyektor",
    specLine: "XGA · 3.300 Lumens",
    ports: "HDMI | USB",
    price: 5300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-x06.jpg",
    id: "eb-x06",
    brand: "Epson",
    name: "Epson EB-X06",
    category: "Proyektor",
    specLine: "XGA · 3.600 Lumens",
    ports: "HDMI | USB | WiFi Optional",
    price: 5750000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-e12.jpg",
    id: "eb-e12",
    brand: "Epson",
    name: "Epson EB-E12",
    category: "Proyektor",
    specLine: "XGA · 3.600 Lumens",
    ports: "Dual HDMI | USB",
    price: 5800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-972.jpg",
    id: "eb-972",
    brand: "Epson",
    name: "Epson EB-972",
    category: "Proyektor",
    specLine: "XGA · 4.100 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 10050000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-1785w.jpg",
    id: "eb-1785w",
    brand: "Epson",
    name: "Epson EB-1785W",
    category: "Proyektor",
    specLine: "WXGA · 3.200 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 15000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-1795f.jpg",
    id: "eb-1795f",
    brand: "Epson",
    name: "Epson EB-1795F",
    category: "Proyektor",
    specLine: "Full HD · 3.200 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 17150000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-ef-61g.jpg",
    id: "ef-61g",
    brand: "Epson",
    name: "Epson EF-61G",
    category: "Proyektor",
    specLine: "Full HD · 700 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 11500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-ef-62n.jpg",
    id: "ef-62n",
    brand: "Epson",
    name: "Epson EF-62N",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 700 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 15500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-ef-71.jpg",
    id: "ef-71",
    brand: "Epson",
    name: "Epson EF-71",
    category: "Proyektor",
    specLine: "Full HD · 700 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 16500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-ef-72.jpg",
    id: "ef-72",
    brand: "Epson",
    name: "Epson EF-72",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 700 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 22500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-w50.jpg",
    id: "eb-w50",
    brand: "Epson",
    name: "Epson EB-W50",
    category: "Proyektor",
    specLine: "WXGA · 3.800 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 12600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-u50.jpg",
    id: "eb-u50",
    brand: "Epson",
    name: "Epson EB-U50",
    category: "Proyektor",
    specLine: "WUXGA · 3.700 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 15000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-982w.jpg",
    id: "eb-982w",
    brand: "Epson",
    name: "Epson EB-982W",
    category: "Proyektor",
    specLine: "WXGA · 4.200 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 17600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l210w.jpg",
    id: "eb-l210w",
    brand: "Epson",
    name: "Epson EB-L210W",
    category: "Proyektor",
    specLine: "WXGA · 4.500 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 24850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l260f.jpg",
    id: "eb-l260f",
    brand: "Epson",
    name: "Epson EB-L260F",
    category: "Proyektor",
    specLine: "Full HD · 4.600 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 26500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l520u.jpg",
    id: "eb-l520u",
    brand: "Epson",
    name: "Epson EB-L520U",
    category: "Proyektor",
    specLine: "WUXGA · 5.200 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 56000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l630u.jpg",
    id: "eb-l630u",
    brand: "Epson",
    name: "Epson EB-L630U",
    category: "Proyektor",
    specLine: "WUXGA · 6.200 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 61000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l690u.jpg",
    id: "eb-l690u",
    brand: "Epson",
    name: "Epson EB-L690U",
    category: "Proyektor",
    specLine: "WUXGA · 6.500 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 66000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l690e.jpg",
    id: "eb-l690e",
    brand: "Epson",
    name: "Epson EB-L690E",
    category: "Proyektor",
    specLine: "WUXGA · 6.500 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 74000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l790u.jpg",
    id: "eb-l790u",
    brand: "Epson",
    name: "Epson EB-L790U",
    category: "Proyektor",
    specLine: "WUXGA · 7.300 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 77500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l890u.jpg",
    id: "eb-l890u",
    brand: "Epson",
    name: "Epson EB-L890U",
    category: "Proyektor",
    specLine: "WUXGA · 8.000 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 85500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l890e.jpg",
    id: "eb-l890e",
    brand: "Epson",
    name: "Epson EB-L890E",
    category: "Proyektor",
    specLine: "WUXGA · 8.000 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 91000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l210sf.jpg",
    id: "eb-l210sf",
    brand: "Epson",
    name: "Epson EB-L210SF",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 28300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l210sw.jpg",
    id: "eb-l210sw",
    brand: "Epson",
    name: "Epson EB-L210SW",
    category: "Proyektor",
    specLine: "Full HD · 4.000 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 25000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l690su.jpg",
    id: "eb-l690su",
    brand: "Epson",
    name: "Epson EB-L690SU",
    category: "Proyektor",
    specLine: "WUXGA · 6.200 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 79600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l690se.jpg",
    id: "eb-l690se",
    brand: "Epson",
    name: "Epson EB-L690SE",
    category: "Proyektor",
    specLine: "WUXGA · 6.000 Lumens",
    ports: "Dual HDMI | LAN | WiFi Optional",
    price: 86000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l790se.jpg",
    id: "eb-l790se",
    brand: "Epson",
    name: "Epson EB-L790SE",
    category: "Proyektor",
    specLine: "WUXGA · 7.000 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 105000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-685w.jpg",
    id: "eb-685w",
    brand: "Epson",
    name: "Epson EB-685W",
    category: "Proyektor",
    specLine: "WXGA · 3.500 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 18900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-685wi.jpg",
    id: "eb-685wi",
    brand: "Epson",
    name: "Epson EB-685Wi",
    category: "Proyektor",
    specLine: "WXGA · 3.500 Lumens",
    ports: "HDMI | Interactive Pen | LAN",
    price: 23300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-760w.jpg",
    id: "eb-760w",
    brand: "Epson",
    name: "Epson EB-760W",
    category: "Proyektor",
    specLine: "WXGA · 4.100 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 26500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-770f.jpg",
    id: "eb-770f",
    brand: "Epson",
    name: "Epson EB-770F",
    category: "Proyektor",
    specLine: "Full HD · 4.100 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 28700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-695wi.jpg",
    id: "eb-695wi",
    brand: "Epson",
    name: "Epson EB-695Wi",
    category: "Proyektor",
    specLine: "WXGA",
    ports: "Interactive Pen",
    price: 27750000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-760wi.jpg",
    id: "eb-760wi",
    brand: "Epson",
    name: "Epson EB-760Wi",
    category: "Proyektor",
    specLine: "WXGA · 4.100 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 31250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-770fi.jpg",
    id: "eb-770fi",
    brand: "Epson",
    name: "Epson EB-770Fi",
    category: "Proyektor",
    specLine: "Full HD · 4.100 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 35350000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-1485fi.jpg",
    id: "eb-1485fi",
    brand: "Epson",
    name: "Epson EB-1485Fi",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | HDBaseT",
    price: 78000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-800f-white.jpg",
    id: "eb-800f-white",
    brand: "Epson",
    name: "Epson EB-800F (WHITE)",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 69000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-805f-black.jpg",
    id: "eb-805f-black",
    brand: "Epson",
    name: "Epson EB-805F (BLACK)",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 69000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-810e-white.jpg",
    id: "eb-810e-white",
    brand: "Epson",
    name: "Epson EB-810E (WHITE)",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 74000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-815e-black.jpg",
    id: "eb-815e-black",
    brand: "Epson",
    name: "Epson EB-815E (BLACK)",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 74000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls650b.jpg",
    id: "eh-ls650b",
    brand: "Epson",
    name: "Epson EH-LS650B",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 3.600 Lumens",
    ports: "Dual HDMI | USB | WiFi",
    price: 39000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls800b-atv.jpg",
    id: "eh-ls800b-atv",
    brand: "Epson",
    name: "Epson EH-LS800B ATV",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 4.000 Lumens",
    ports: "Dual HDMI | USB | WiFi",
    price: 57500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls670b.jpg",
    id: "eh-ls670b",
    brand: "Epson",
    name: "Epson EH-LS670B",
    category: "Proyektor",
    specLine: "Full HD · 3.600 Lumens",
    ports: "3 HDMI | WiFi",
    price: 39000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls9000w.jpg",
    id: "eh-ls9000w",
    brand: "Epson",
    name: "Epson EH-LS9000W",
    category: "Proyektor",
    specLine: "Full HD · 2.200 Lumens",
    ports: "Dual HDMI | LAN",
    price: 139000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ql3000w-std.jpg",
    id: "eh-ql3000w-std",
    brand: "Epson",
    name: "Epson EH-QL3000W STD",
    category: "Proyektor",
    specLine: "4K · 6.000 Lumens",
    ports: "HDMI | USB | LAN",
    price: 235000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-co-fh01.jpg",
    id: "co-fh01",
    brand: "Epson",
    name: "Epson CO-FH01",
    category: "Proyektor",
    specLine: "Full HD · 3.000 Lumens",
    ports: "HDMI | USB | WiFi Optional",
    price: 7250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-co-fh02.jpg",
    id: "co-fh02",
    brand: "Epson",
    name: "Epson CO-FH02",
    category: "Proyektor",
    specLine: "Full HD · 3.000 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 9900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-tw6250.jpg",
    id: "eh-tw6250",
    brand: "Epson",
    name: "Epson EH-TW6250",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 2.800 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 19400000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-tw7000.jpg",
    id: "eh-tw7000",
    brand: "Epson",
    name: "Epson EH-TW7000",
    category: "Proyektor",
    specLine: "Full HD · 3.000 Lumens",
    ports: "Dual HDMI | USB | WiFi Optional",
    price: 21200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-tw9400.jpg",
    id: "eh-tw9400",
    brand: "Epson",
    name: "Epson EH-TW9400",
    category: "Proyektor",
    specLine: "Full HD · 2.600 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 43350000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls12000b.jpg",
    id: "eh-ls12000b",
    brand: "Epson",
    name: "Epson EH-LS12000B",
    category: "Proyektor",
    specLine: "Full HD · 2.700 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 92500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-elpap11.jpg",
    id: "elpap11",
    brand: "Epson",
    name: "Epson ELPAP11",
    category: "Proyektor",
    specLine: "Modul Wireless LAN untuk Proyektor",
    ports: "802.11 a/b/g/n Dual Band (2.4GHz/5GHz)",
    price: 1700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-elpap12.jpg",
    id: "elpap12",
    brand: "Epson",
    name: "Epson ELPAP12",
    category: "Proyektor",
    specLine: "Wireless Dongle Android TV",
    ports: "Android 9.0 Pie, Chromecast Built-In",
    price: 1700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-elpdc21.jpg",
    id: "elpdc21",
    brand: "Epson",
    name: "Epson ELPDC21",
    category: "Proyektor",
    specLine: "Document Camera, 2MP",
    ports: "12x Optical Zoom, 10x Digital Zoom",
    price: 7600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-elpmb62.jpg",
    id: "elpmb62",
    brand: "Epson",
    name: "Epson ELPMB62",
    category: "Proyektor",
    specLine: "Setting Plate / Wall Mount Bracket",
    ports: "Aksesoris pemasangan proyektor interaktif",
    price: 2600000,
    priceIsEstimate: true,
    icon: "projector"
  },

  /* ====================================================================
     PRODUK TAMBAHAN — dari product_new_website.xlsx (31 item, beragam
     merek: BenQ, Acer, Hisense, HP, LG, Panasonic, ViewSonic, XGIMI,
     Xiaomi). Foto sudah lengkap untuk semua produk di batch ini.
     ==================================================================== */
  {
    image: "assets/img/produk-benq-mx560c.jpg",
    id: "benq-mx560c",
    brand: "BenQ",
    name: "BenQ MX560C",
    category: "Proyektor",
    specLine: "XGA · 4.000 Lumens",
    ports: "HDMI | VGA",
    price: 5500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-benq-mw560c.jpg",
    id: "benq-mw560c",
    brand: "BenQ",
    name: "BenQ MW560C",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "HDMI | VGA",
    price: 6500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-benq-gv50.jpg",
    id: "benq-gv50",
    brand: "BenQ",
    name: "BenQ GV50",
    category: "Proyektor",
    specLine: "Full HD · 500 Lumens",
    ports: "HDMI | USB | Bluetooth",
    price: 11000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-benq-w2700i.jpg",
    id: "benq-w2700i",
    brand: "BenQ",
    name: "BenQ W2700i",
    category: "Proyektor",
    specLine: "2.000 Lumens",
    ports: "Dual HDMI | VGA | Smart TV Built-in",
    price: 29800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-acer-vero-xl2330w.jpg",
    id: "acer-vero-xl2330w",
    brand: "Acer",
    name: "Acer Vero XL2330W",
    category: "Proyektor",
    specLine: "WXGA · 5.000 Lumens",
    ports: "Dual HDMI",
    price: 13800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-hisense-px3-pro-lx-3-pro.jpg",
    id: "hisense-px3-pro-lx-3-pro",
    brand: "Hisense",
    name: "Hisense PX3-PRO / LX-3 Pro",
    category: "Proyektor",
    specLine: "4K · 3.000 Lumens",
    ports: "HDMI | Bluetooth | Smart TV Built-in",
    price: 49000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-hisense-c2-ultra.jpg",
    id: "hisense-c2-ultra",
    brand: "Hisense",
    name: "Hisense C2 Ultra",
    category: "Proyektor",
    specLine: "4K · 3.000 Lumens",
    ports: "HDMI | Bluetooth",
    price: 49500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-hisense-m2-pro.jpg",
    id: "hisense-m2-pro",
    brand: "Hisense",
    name: "Hisense M2 Pro",
    category: "Proyektor",
    specLine: "4K · 1.300 Lumens",
    ports: "Bluetooth | WiFi",
    price: 30500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-hp-cc500.jpg",
    id: "hp-cc500",
    brand: "HP",
    name: "HP CC500",
    category: "Proyektor",
    specLine: "Full HD · 500 Lumens",
    ports: "Smart TV Built-in",
    price: 3500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-lg-hu710pw.jpg",
    id: "lg-hu710pw",
    brand: "LG",
    name: "LG HU710PW",
    category: "Proyektor",
    specLine: "4K · 2.000 Lumens",
    ports: "HDMI",
    price: 35500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-lg-hu915qe.jpg",
    id: "lg-hu915qe",
    brand: "LG",
    name: "LG HU915QE",
    category: "Proyektor",
    specLine: "4K · 3.700 Lumens",
    ports: "HDMI | WiFi",
    price: 41000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-panasonic-pt-lb356.jpg",
    id: "panasonic-pt-lb356",
    brand: "Panasonic",
    name: "Panasonic PT-LB356",
    category: "Proyektor",
    specLine: "XGA · 3.300 Lumens",
    ports: "HDMI",
    price: 8900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-panasonic-pt-lmx460.jpg",
    id: "panasonic-pt-lmx460",
    brand: "Panasonic",
    name: "Panasonic PT-LMX460",
    category: "Proyektor",
    specLine: "XGA · 4.600 Lumens",
    ports: "HDMI",
    price: 18500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-panasonic-pt-lmw460.jpg",
    id: "panasonic-pt-lmw460",
    brand: "Panasonic",
    name: "Panasonic PT-LMW460",
    category: "Proyektor",
    specLine: "WXGA · 4.600 Lumens",
    ports: "HDMI | WiFi",
    price: 31500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-panasonic-pt-lmz460.jpg",
    id: "panasonic-pt-lmz460",
    brand: "Panasonic",
    name: "Panasonic PT-LMZ460",
    category: "Proyektor",
    specLine: "WUXGA · 4.600 Lumens",
    ports: "HDMI | WiFi",
    price: 34500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lx60hd.jpg",
    id: "viewsonic-lx60hd",
    brand: "ViewSonic",
    name: "ViewSonic LX60HD",
    category: "Proyektor",
    specLine: "Full HD · 630 Lumens",
    ports: "HDMI | USB | Smart TV Built-in",
    price: 4600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-m1-max.jpg",
    id: "viewsonic-m1-max",
    brand: "ViewSonic",
    name: "ViewSonic M1 Max",
    category: "Proyektor",
    specLine: "Full HD · 500 Lumens",
    ports: "HDMI | USB | Smart TV Built-in",
    price: 7700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-sp3.jpg",
    id: "viewsonic-sp3",
    brand: "ViewSonic",
    name: "ViewSonic SP3",
    category: "Proyektor",
    specLine: "SVGA · 4.800 Lumens",
    ports: "HDMI | VGA",
    price: 4500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-sp6.jpg",
    id: "viewsonic-sp6",
    brand: "ViewSonic",
    name: "ViewSonic SP6",
    category: "Proyektor",
    specLine: "XGA · 4.800 Lumens",
    ports: "HDMI | VGA",
    price: 5100000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-sp7.jpg",
    id: "viewsonic-sp7",
    brand: "ViewSonic",
    name: "ViewSonic SP7",
    category: "Proyektor",
    specLine: "WXGA · 4.800 Lumens",
    ports: "HDMI | VGA",
    price: 5600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-ps502x.jpg",
    id: "viewsonic-ps502x",
    brand: "ViewSonic",
    name: "ViewSonic PS502X",
    category: "Proyektor",
    specLine: "XGA · 4.000 Lumens",
    ports: "Dual HDMI",
    price: 8800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-ps502w.jpg",
    id: "viewsonic-ps502w",
    brand: "ViewSonic",
    name: "ViewSonic PS502W",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Dual HDMI",
    price: 9600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lsd500hd.jpg",
    id: "viewsonic-lsd500hd",
    brand: "ViewSonic",
    name: "ViewSonic LSD500HD",
    category: "Proyektor",
    specLine: "Full HD · 5.500 Lumens",
    ports: "Hubungi kami untuk spesifikasi lengkap",
    price: 19800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lsd600w.jpg",
    id: "viewsonic-lsd600w",
    brand: "ViewSonic",
    name: "ViewSonic LSD600W",
    category: "Proyektor",
    specLine: "WXGA · 6.000 Lumens",
    ports: "Hubungi kami untuk spesifikasi lengkap",
    price: 17250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lsd400w.jpg",
    id: "viewsonic-lsd400w",
    brand: "ViewSonic",
    name: "ViewSonic LSD400W",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Hubungi kami untuk spesifikasi lengkap",
    price: 12250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lsd400w-pj-wpd-900.jpg",
    id: "viewsonic-lsd400w-pj-wpd-900",
    brand: "ViewSonic",
    name: "ViewSonic LSD400W + PJ-WPD-900",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Hubungi kami untuk spesifikasi lengkap",
    price: 13500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-x2000b-4k.jpg",
    id: "viewsonic-x2000b-4k",
    brand: "ViewSonic",
    name: "ViewSonic X2000B-4K",
    category: "Proyektor",
    specLine: "4K · 2.000 Lumens",
    ports: "HDMI | VGA | Bluetooth",
    price: 39500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-tb5030-tkdn.jpg",
    id: "viewsonic-tb5030-tkdn",
    brand: "ViewSonic",
    name: "ViewSonic TB5030 TKDN",
    category: "Proyektor",
    specLine: "XGA · 4.500 Lumens",
    ports: "HDMI | VGA",
    price: 5800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-xgimi-mogo-2-pro.jpg",
    id: "xgimi-mogo-2-pro",
    brand: "XGIMI",
    name: "XGIMI MOGO 2 PRO",
    category: "Proyektor",
    specLine: "Full HD · 500 Lumens",
    ports: "HDMI | Bluetooth | Smart TV Built-in",
    price: 7900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-xiaomi-l1.jpg",
    id: "xiaomi-l1",
    brand: "Xiaomi",
    name: "Xiaomi L1",
    category: "Proyektor",
    specLine: "Full HD · 200 Lumens",
    ports: "Bluetooth | Smart TV Built-in",
    price: 3500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-xiaomi-l1-pro.jpg",
    id: "xiaomi-l1-pro",
    brand: "Xiaomi",
    name: "Xiaomi L1 Pro",
    category: "Proyektor",
    specLine: "Full HD · 400 Lumens",
    ports: "Bluetooth | Smart TV Built-in",
    price: 4900000,
    priceIsEstimate: true,
    icon: "projector"
  }
];
