/* ====================================================================
   KATALOG PRODUK — satu tempat untuk semua data produk yang bisa dibeli.
   ====================================================================
   Cara nambah produk baru: copy salah satu blok { ... } di bawah,
   ganti isinya, kasih "id" yang unik (huruf kecil, tanpa spasi).

   Field "priceIsEstimate: true" artinya harga yang tampil adalah
   estimasi/harga promo terbatas — harga final tetap dikonfirmasi
   admin lewat WhatsApp saat checkout (jadi aman, gak akan salah kasih
   harga pasti ke customer untuk produk yang harganya bisa berubah).

   Struktur ini sengaja dipisah dari logic (js/cart.js) dan tampilan
   (index.html) supaya gampang nanti kalau mau disambungkan ke
   database/backend asli — tinggal ganti PRODUCTS ini jadi hasil
   fetch() dari API, sisanya (cart, checkout, hitung total) gak perlu
   diubah sama sekali.
   ==================================================================== */
const PRODUCTS = [
  {
    image: "assets/img/produk-epson-eb-e600.jpg",
    id: "eb-e600",
    brand: "Epson",
    name: "Epson EB-E600",
    category: "Proyektor",
    specLine: "XGA · 3.400 Lumens",
    ports: "HDMI | VGA In/Out, No Zoom In/Out",
    price: 5400000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-x600.jpg",
    id: "eb-x600",
    brand: "Epson",
    name: "Epson EB-X600",
    category: "Proyektor",
    specLine: "XGA · 3.600 Lumens",
    ports: "USB | HDMI | VGA In/Out",
    price: 5800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-w55.jpg",
    id: "eb-w55",
    brand: "Epson",
    name: "Epson EB-W55",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Dual HDMI | USB | WiFi",
    price: 8500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-x52.jpg",
    id: "eb-x52",
    brand: "Epson",
    name: "Epson EB-X52",
    category: "Proyektor",
    specLine: "XGA · 3.800 Lumens",
    ports: "USB | Dual HDMI",
    price: 6600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-w53.jpg",
    id: "eb-w53",
    brand: "Epson",
    name: "Epson EB-W53",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "HDMI, No Zoom In/Out",
    price: 7200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-fh54.jpg",
    id: "eb-fh54",
    brand: "Epson",
    name: "Epson EB-FH54",
    category: "Proyektor",
    specLine: "Full HD · 4.100 Lumens",
    ports: "USB | Dual HDMI | WiFi",
    price: 13250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-infocus-in0004sl.jpg",
    id: "infocus-in0004sl",
    brand: "InFocus",
    name: "InFocus IN0004SL",
    category: "Proyektor",
    specLine: "XGA · 4.000 Lumens",
    ports: "HDMI | VGA",
    price: 4900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-spc-p100.jpg",
    id: "spc-p100",
    brand: "SPC",
    name: "SPC P100",
    category: "Proyektor",
    specLine: "XGA · 4.200 Lumens",
    ports: "HDMI | VGA · Bersertifikat TKDN",
    price: 3900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-2065.jpg",
    id: "eb-2065",
    brand: "Epson",
    name: "Epson EB-2065",
    category: "Proyektor",
    specLine: "XGA · 5.500 Lumens",
    ports: "HDMI | USB | LAN",
    price: 21000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-2155w.jpg",
    id: "eb-2155w",
    brand: "Epson",
    name: "Epson EB-2155W",
    category: "Proyektor",
    specLine: "WXGA · 5.000 Lumens",
    ports: "HDMI | USB | LAN",
    price: 23000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-epson-eb-2265u.jpg",
    id: "eb-2265u",
    brand: "Epson",
    name: "Epson EB-2265U",
    category: "Proyektor",
    specLine: "WUXGA · 5.500 Lumens",
    ports: "HDMI | USB | LAN",
    price: 31000000,
    priceIsEstimate: true,
    icon: "projector"
  },

  /* ====================================================================
     PRODUK TAMBAHAN — dari PRICELIST_WEB.xlsx (54 item, semua Epson).
     Foto sudah lengkap untuk semua produk di batch ini.
     ==================================================================== */
  {
    image: "assets/img/produk-eb-e01.jpg",
    id: "eb-e01",
    brand: "Epson",
    name: "Epson EB-E01",
    category: "Proyektor",
    specLine: "XGA · 3.300 Lumens",
    ports: "HDMI | USB",
    price: 5300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-x06.jpg",
    id: "eb-x06",
    brand: "Epson",
    name: "Epson EB-X06",
    category: "Proyektor",
    specLine: "XGA · 3.600 Lumens",
    ports: "HDMI | USB | WiFi Optional",
    price: 5750000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-e12.jpg",
    id: "eb-e12",
    brand: "Epson",
    name: "Epson EB-E12",
    category: "Proyektor",
    specLine: "XGA · 3.600 Lumens",
    ports: "Dual HDMI | USB",
    price: 5800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-972.jpg",
    id: "eb-972",
    brand: "Epson",
    name: "Epson EB-972",
    category: "Proyektor",
    specLine: "XGA · 4.100 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 10050000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-1785w.jpg",
    id: "eb-1785w",
    brand: "Epson",
    name: "Epson EB-1785W",
    category: "Proyektor",
    specLine: "WXGA · 3.200 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 15000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-1795f.jpg",
    id: "eb-1795f",
    brand: "Epson",
    name: "Epson EB-1795F",
    category: "Proyektor",
    specLine: "Full HD · 3.200 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 17150000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-ef-61g.jpg",
    id: "ef-61g",
    brand: "Epson",
    name: "Epson EF-61G",
    category: "Proyektor",
    specLine: "Full HD · 700 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 11500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-ef-62n.jpg",
    id: "ef-62n",
    brand: "Epson",
    name: "Epson EF-62N",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 700 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 15500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-ef-71.jpg",
    id: "ef-71",
    brand: "Epson",
    name: "Epson EF-71",
    category: "Proyektor",
    specLine: "Full HD · 700 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 16500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-ef-72.jpg",
    id: "ef-72",
    brand: "Epson",
    name: "Epson EF-72",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 700 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 22500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-w50.jpg",
    id: "eb-w50",
    brand: "Epson",
    name: "Epson EB-W50",
    category: "Proyektor",
    specLine: "WXGA · 3.800 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 12600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-u50.jpg",
    id: "eb-u50",
    brand: "Epson",
    name: "Epson EB-U50",
    category: "Proyektor",
    specLine: "WUXGA · 3.700 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 15000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-982w.jpg",
    id: "eb-982w",
    brand: "Epson",
    name: "Epson EB-982W",
    category: "Proyektor",
    specLine: "WXGA · 4.200 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 17600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l210w.jpg",
    id: "eb-l210w",
    brand: "Epson",
    name: "Epson EB-L210W",
    category: "Proyektor",
    specLine: "WXGA · 4.500 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 24850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l260f.jpg",
    id: "eb-l260f",
    brand: "Epson",
    name: "Epson EB-L260F",
    category: "Proyektor",
    specLine: "Full HD · 4.600 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 26500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l520u.jpg",
    id: "eb-l520u",
    brand: "Epson",
    name: "Epson EB-L520U",
    category: "Proyektor",
    specLine: "WUXGA · 5.200 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 56000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l630u.jpg",
    id: "eb-l630u",
    brand: "Epson",
    name: "Epson EB-L630U",
    category: "Proyektor",
    specLine: "WUXGA · 6.200 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 61000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l690u.jpg",
    id: "eb-l690u",
    brand: "Epson",
    name: "Epson EB-L690U",
    category: "Proyektor",
    specLine: "WUXGA · 6.500 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 66000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l690e.jpg",
    id: "eb-l690e",
    brand: "Epson",
    name: "Epson EB-L690E",
    category: "Proyektor",
    specLine: "WUXGA · 6.500 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 74000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l790u.jpg",
    id: "eb-l790u",
    brand: "Epson",
    name: "Epson EB-L790U",
    category: "Proyektor",
    specLine: "WUXGA · 7.300 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 77500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l890u.jpg",
    id: "eb-l890u",
    brand: "Epson",
    name: "Epson EB-L890U",
    category: "Proyektor",
    specLine: "WUXGA · 8.000 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 85500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l890e.jpg",
    id: "eb-l890e",
    brand: "Epson",
    name: "Epson EB-L890E",
    category: "Proyektor",
    specLine: "WUXGA · 8.000 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 91000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l210sf.jpg",
    id: "eb-l210sf",
    brand: "Epson",
    name: "Epson EB-L210SF",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 28300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l210sw.jpg",
    id: "eb-l210sw",
    brand: "Epson",
    name: "Epson EB-L210SW",
    category: "Proyektor",
    specLine: "Full HD · 4.000 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 25000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l690su.jpg",
    id: "eb-l690su",
    brand: "Epson",
    name: "Epson EB-L690SU",
    category: "Proyektor",
    specLine: "WUXGA · 6.200 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 79600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l690se.jpg",
    id: "eb-l690se",
    brand: "Epson",
    name: "Epson EB-L690SE",
    category: "Proyektor",
    specLine: "WUXGA · 6.000 Lumens",
    ports: "Dual HDMI | LAN | WiFi Optional",
    price: 86000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-l790se.jpg",
    id: "eb-l790se",
    brand: "Epson",
    name: "Epson EB-L790SE",
    category: "Proyektor",
    specLine: "WUXGA · 7.000 Lumens",
    ports: "Dual HDMI | LAN | WiFi",
    price: 105000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-685w.jpg",
    id: "eb-685w",
    brand: "Epson",
    name: "Epson EB-685W",
    category: "Proyektor",
    specLine: "WXGA · 3.500 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 18900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-685wi.jpg",
    id: "eb-685wi",
    brand: "Epson",
    name: "Epson EB-685Wi",
    category: "Proyektor",
    specLine: "WXGA · 3.500 Lumens",
    ports: "HDMI | Interactive Pen | LAN",
    price: 23300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-760w.jpg",
    id: "eb-760w",
    brand: "Epson",
    name: "Epson EB-760W",
    category: "Proyektor",
    specLine: "WXGA · 4.100 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 26500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-770f.jpg",
    id: "eb-770f",
    brand: "Epson",
    name: "Epson EB-770F",
    category: "Proyektor",
    specLine: "Full HD · 4.100 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 28700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-695wi.jpg",
    id: "eb-695wi",
    brand: "Epson",
    name: "Epson EB-695Wi",
    category: "Proyektor",
    specLine: "WXGA",
    ports: "Interactive Pen",
    price: 27750000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-760wi.jpg",
    id: "eb-760wi",
    brand: "Epson",
    name: "Epson EB-760Wi",
    category: "Proyektor",
    specLine: "WXGA · 4.100 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 31250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-770fi.jpg",
    id: "eb-770fi",
    brand: "Epson",
    name: "Epson EB-770Fi",
    category: "Proyektor",
    specLine: "Full HD · 4.100 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 35350000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-1485fi.jpg",
    id: "eb-1485fi",
    brand: "Epson",
    name: "Epson EB-1485Fi",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | HDBaseT",
    price: 78000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-800f-white.jpg",
    id: "eb-800f-white",
    brand: "Epson",
    name: "Epson EB-800F (WHITE)",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 69000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-805f-black.jpg",
    id: "eb-805f-black",
    brand: "Epson",
    name: "Epson EB-805F (BLACK)",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 69000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-810e-white.jpg",
    id: "eb-810e-white",
    brand: "Epson",
    name: "Epson EB-810E (WHITE)",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 74000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eb-815e-black.jpg",
    id: "eb-815e-black",
    brand: "Epson",
    name: "Epson EB-815E (BLACK)",
    category: "Proyektor",
    specLine: "Full HD · 5.000 Lumens",
    ports: "3 HDMI | USB | LAN",
    price: 74000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls650b.jpg",
    id: "eh-ls650b",
    brand: "Epson",
    name: "Epson EH-LS650B",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 3.600 Lumens",
    ports: "Dual HDMI | USB | WiFi",
    price: 39000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls800b-atv.jpg",
    id: "eh-ls800b-atv",
    brand: "Epson",
    name: "Epson EH-LS800B ATV",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 4.000 Lumens",
    ports: "Dual HDMI | USB | WiFi",
    price: 57500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls670b.jpg",
    id: "eh-ls670b",
    brand: "Epson",
    name: "Epson EH-LS670B",
    category: "Proyektor",
    specLine: "Full HD · 3.600 Lumens",
    ports: "3 HDMI | WiFi",
    price: 39000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls9000w.jpg",
    id: "eh-ls9000w",
    brand: "Epson",
    name: "Epson EH-LS9000W",
    category: "Proyektor",
    specLine: "Full HD · 2.200 Lumens",
    ports: "Dual HDMI | LAN",
    price: 139000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ql3000w-std.jpg",
    id: "eh-ql3000w-std",
    brand: "Epson",
    name: "Epson EH-QL3000W STD",
    category: "Proyektor",
    specLine: "4K · 6.000 Lumens",
    ports: "HDMI | USB | LAN",
    price: 235000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-co-fh01.jpg",
    id: "co-fh01",
    brand: "Epson",
    name: "Epson CO-FH01",
    category: "Proyektor",
    specLine: "Full HD · 3.000 Lumens",
    ports: "HDMI | USB | WiFi Optional",
    price: 7250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-co-fh02.jpg",
    id: "co-fh02",
    brand: "Epson",
    name: "Epson CO-FH02",
    category: "Proyektor",
    specLine: "Full HD · 3.000 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 9900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-tw6250.jpg",
    id: "eh-tw6250",
    brand: "Epson",
    name: "Epson EH-TW6250",
    category: "Proyektor",
    specLine: "4K Pro-UHD · 2.800 Lumens",
    ports: "HDMI | USB | WiFi",
    price: 19400000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-tw7000.jpg",
    id: "eh-tw7000",
    brand: "Epson",
    name: "Epson EH-TW7000",
    category: "Proyektor",
    specLine: "Full HD · 3.000 Lumens",
    ports: "Dual HDMI | USB | WiFi Optional",
    price: 21200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-tw9400.jpg",
    id: "eh-tw9400",
    brand: "Epson",
    name: "Epson EH-TW9400",
    category: "Proyektor",
    specLine: "Full HD · 2.600 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 43350000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-eh-ls12000b.jpg",
    id: "eh-ls12000b",
    brand: "Epson",
    name: "Epson EH-LS12000B",
    category: "Proyektor",
    specLine: "Full HD · 2.700 Lumens",
    ports: "Dual HDMI | USB | LAN",
    price: 92500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-elpap11.jpg",
    id: "elpap11",
    brand: "Epson",
    name: "Epson ELPAP11",
    category: "Proyektor",
    specLine: "Modul Wireless LAN untuk Proyektor",
    ports: "802.11 a/b/g/n Dual Band (2.4GHz/5GHz)",
    price: 1700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-elpap12.jpg",
    id: "elpap12",
    brand: "Epson",
    name: "Epson ELPAP12",
    category: "Proyektor",
    specLine: "Wireless Dongle Android TV",
    ports: "Android 9.0 Pie, Chromecast Built-In",
    price: 1700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-elpdc21.jpg",
    id: "elpdc21",
    brand: "Epson",
    name: "Epson ELPDC21",
    category: "Proyektor",
    specLine: "Document Camera, 2MP",
    ports: "12x Optical Zoom, 10x Digital Zoom",
    price: 7600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-elpmb62.jpg",
    id: "elpmb62",
    brand: "Epson",
    name: "Epson ELPMB62",
    category: "Proyektor",
    specLine: "Setting Plate / Wall Mount Bracket",
    ports: "Aksesoris pemasangan proyektor interaktif",
    price: 2600000,
    priceIsEstimate: true,
    icon: "projector"
  },

  /* ====================================================================
     PRODUK TAMBAHAN — dari product_new_website.xlsx (31 item, beragam
     merek: BenQ, Acer, Hisense, HP, LG, Panasonic, ViewSonic, XGIMI,
     Xiaomi). Foto sudah lengkap untuk semua produk di batch ini.
     ==================================================================== */
  {
    image: "assets/img/produk-benq-mx560c.jpg",
    id: "benq-mx560c",
    brand: "BenQ",
    name: "BenQ MX560C",
    category: "Proyektor",
    specLine: "XGA · 4.000 Lumens",
    ports: "HDMI | VGA",
    price: 5500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-benq-mw560c.jpg",
    id: "benq-mw560c",
    brand: "BenQ",
    name: "BenQ MW560C",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "HDMI | VGA",
    price: 6500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-benq-gv50.jpg",
    id: "benq-gv50",
    brand: "BenQ",
    name: "BenQ GV50",
    category: "Proyektor",
    specLine: "Full HD · 500 Lumens",
    ports: "HDMI | USB | Bluetooth",
    price: 11000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-benq-w2700i.jpg",
    id: "benq-w2700i",
    brand: "BenQ",
    name: "BenQ W2700i",
    category: "Proyektor",
    specLine: "2.000 Lumens",
    ports: "Dual HDMI | VGA | Smart TV Built-in",
    price: 29800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-acer-vero-xl2330w.jpg",
    id: "acer-vero-xl2330w",
    brand: "Acer",
    name: "Acer Vero XL2330W",
    category: "Proyektor",
    specLine: "WXGA · 5.000 Lumens",
    ports: "Dual HDMI",
    price: 13800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-hisense-px3-pro-lx-3-pro.jpg",
    id: "hisense-px3-pro-lx-3-pro",
    brand: "Hisense",
    name: "Hisense PX3-PRO / LX-3 Pro",
    category: "Proyektor",
    specLine: "4K · 3.000 Lumens",
    ports: "HDMI | Bluetooth | Smart TV Built-in",
    price: 49000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-hisense-c2-ultra.jpg",
    id: "hisense-c2-ultra",
    brand: "Hisense",
    name: "Hisense C2 Ultra",
    category: "Proyektor",
    specLine: "4K · 3.000 Lumens",
    ports: "HDMI | Bluetooth",
    price: 49500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-hisense-m2-pro.jpg",
    id: "hisense-m2-pro",
    brand: "Hisense",
    name: "Hisense M2 Pro",
    category: "Proyektor",
    specLine: "4K · 1.300 Lumens",
    ports: "Bluetooth | WiFi",
    price: 30500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-hp-cc500.jpg",
    id: "hp-cc500",
    brand: "HP",
    name: "HP CC500",
    category: "Proyektor",
    specLine: "Full HD · 500 Lumens",
    ports: "Smart TV Built-in",
    price: 3500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-lg-hu710pw.jpg",
    id: "lg-hu710pw",
    brand: "LG",
    name: "LG HU710PW",
    category: "Proyektor",
    specLine: "4K · 2.000 Lumens",
    ports: "HDMI",
    price: 35500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-lg-hu915qe.jpg",
    id: "lg-hu915qe",
    brand: "LG",
    name: "LG HU915QE",
    category: "Proyektor",
    specLine: "4K · 3.700 Lumens",
    ports: "HDMI | WiFi",
    price: 41000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-panasonic-pt-lb356.jpg",
    id: "panasonic-pt-lb356",
    brand: "Panasonic",
    name: "Panasonic PT-LB356",
    category: "Proyektor",
    specLine: "XGA · 3.300 Lumens",
    ports: "HDMI",
    price: 8900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-panasonic-pt-lmx460.jpg",
    id: "panasonic-pt-lmx460",
    brand: "Panasonic",
    name: "Panasonic PT-LMX460",
    category: "Proyektor",
    specLine: "XGA · 4.600 Lumens",
    ports: "HDMI",
    price: 18500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-panasonic-pt-lmw460.jpg",
    id: "panasonic-pt-lmw460",
    brand: "Panasonic",
    name: "Panasonic PT-LMW460",
    category: "Proyektor",
    specLine: "WXGA · 4.600 Lumens",
    ports: "HDMI | WiFi",
    price: 31500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-panasonic-pt-lmz460.jpg",
    id: "panasonic-pt-lmz460",
    brand: "Panasonic",
    name: "Panasonic PT-LMZ460",
    category: "Proyektor",
    specLine: "WUXGA · 4.600 Lumens",
    ports: "HDMI | WiFi",
    price: 34500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lx60hd.jpg",
    id: "viewsonic-lx60hd",
    brand: "ViewSonic",
    name: "ViewSonic LX60HD",
    category: "Proyektor",
    specLine: "Full HD · 630 Lumens",
    ports: "HDMI | USB | Smart TV Built-in",
    price: 4600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-m1-max.jpg",
    id: "viewsonic-m1-max",
    brand: "ViewSonic",
    name: "ViewSonic M1 Max",
    category: "Proyektor",
    specLine: "Full HD · 500 Lumens",
    ports: "HDMI | USB | Smart TV Built-in",
    price: 7700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-sp3.jpg",
    id: "viewsonic-sp3",
    brand: "ViewSonic",
    name: "ViewSonic SP3",
    category: "Proyektor",
    specLine: "SVGA · 4.800 Lumens",
    ports: "HDMI | VGA",
    price: 4500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-sp6.jpg",
    id: "viewsonic-sp6",
    brand: "ViewSonic",
    name: "ViewSonic SP6",
    category: "Proyektor",
    specLine: "XGA · 4.800 Lumens",
    ports: "HDMI | VGA",
    price: 5100000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-sp7.jpg",
    id: "viewsonic-sp7",
    brand: "ViewSonic",
    name: "ViewSonic SP7",
    category: "Proyektor",
    specLine: "WXGA · 4.800 Lumens",
    ports: "HDMI | VGA",
    price: 5600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-ps502x.jpg",
    id: "viewsonic-ps502x",
    brand: "ViewSonic",
    name: "ViewSonic PS502X",
    category: "Proyektor",
    specLine: "XGA · 4.000 Lumens",
    ports: "Dual HDMI",
    price: 8800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-ps502w.jpg",
    id: "viewsonic-ps502w",
    brand: "ViewSonic",
    name: "ViewSonic PS502W",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Dual HDMI",
    price: 9600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lsd500hd.jpg",
    id: "viewsonic-lsd500hd",
    brand: "ViewSonic",
    name: "ViewSonic LSD500HD",
    category: "Proyektor",
    specLine: "Full HD · 5.500 Lumens",
    ports: "Hubungi kami untuk spesifikasi lengkap",
    price: 19800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lsd600w.jpg",
    id: "viewsonic-lsd600w",
    brand: "ViewSonic",
    name: "ViewSonic LSD600W",
    category: "Proyektor",
    specLine: "WXGA · 6.000 Lumens",
    ports: "Hubungi kami untuk spesifikasi lengkap",
    price: 17250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lsd400w.jpg",
    id: "viewsonic-lsd400w",
    brand: "ViewSonic",
    name: "ViewSonic LSD400W",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Hubungi kami untuk spesifikasi lengkap",
    price: 12250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-lsd400w-pj-wpd-900.jpg",
    id: "viewsonic-lsd400w-pj-wpd-900",
    brand: "ViewSonic",
    name: "ViewSonic LSD400W + PJ-WPD-900",
    category: "Proyektor",
    specLine: "WXGA · 4.000 Lumens",
    ports: "Hubungi kami untuk spesifikasi lengkap",
    price: 13500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-x2000b-4k.jpg",
    id: "viewsonic-x2000b-4k",
    brand: "ViewSonic",
    name: "ViewSonic X2000B-4K",
    category: "Proyektor",
    specLine: "4K · 2.000 Lumens",
    ports: "HDMI | VGA | Bluetooth",
    price: 39500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-viewsonic-tb5030-tkdn.jpg",
    id: "viewsonic-tb5030-tkdn",
    brand: "ViewSonic",
    name: "ViewSonic TB5030 TKDN",
    category: "Proyektor",
    specLine: "XGA · 4.500 Lumens",
    ports: "HDMI | VGA",
    price: 5800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-xgimi-mogo-2-pro.jpg",
    id: "xgimi-mogo-2-pro",
    brand: "XGIMI",
    name: "XGIMI MOGO 2 PRO",
    category: "Proyektor",
    specLine: "Full HD · 500 Lumens",
    ports: "HDMI | Bluetooth | Smart TV Built-in",
    price: 7900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-xiaomi-l1.jpg",
    id: "xiaomi-l1",
    brand: "Xiaomi",
    name: "Xiaomi L1",
    category: "Proyektor",
    specLine: "Full HD · 200 Lumens",
    ports: "Bluetooth | Smart TV Built-in",
    price: 3500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/produk-xiaomi-l1-pro.jpg",
    id: "xiaomi-l1-pro",
    brand: "Xiaomi",
    name: "Xiaomi L1 Pro",
    category: "Proyektor",
    specLine: "Full HD · 400 Lumens",
    ports: "Bluetooth | Smart TV Built-in",
    price: 4900000,
    priceIsEstimate: true,
    icon: "projector"
  },

  /* ====================================================================
     LAYAR PROYEKTOR OPTIMA — dari product_new_website_screen.xlsx (31
     item). Kategori "Layar Proyektor", beda dari "Proyektor" -- ini
     yang bikin filter Kategori di halaman produk sekarang ada 2
     pilihan. 4 varian "Manual Screen" (70/84/96/120") belum ada foto
     yang cocok dilampirkan, jadi masih pakai ikon placeholder
     ("image: null") sampai fotonya dikasih.
     ==================================================================== */
  {
    image: "assets/img/optima-manual-screen.jpg",
    id: "optima-manual-screen-70",
    brand: "Optima",
    name: "Optima Manual Screen 70\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 70 Inch",
    ports: "178 cm x 178 cm",
    price: 450000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-manual-screen.jpg",
    id: "optima-manual-screen-84",
    brand: "Optima",
    name: "Optima Manual Screen 84\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 84 Inch",
    ports: "213 cm x 213 cm",
    price: 750000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-manual-screen.jpg",
    id: "optima-manual-screen-96",
    brand: "Optima",
    name: "Optima Manual Screen 96\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 96 Inch",
    ports: "244 cm x 244 cm",
    price: 1000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-manual-screen.jpg",
    id: "optima-manual-screen-120",
    brand: "Optima",
    name: "Optima Manual Screen 120\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 120 Inch",
    ports: "305 cm x 305 cm",
    price: 1750000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-tripod-screen.jpg",
    id: "optima-tripod-screen-70",
    brand: "Optima",
    name: "Optima Tripod Screen 70\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 70 Inch",
    ports: "178 cm x 178 cm",
    price: 550000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-tripod-screen.jpg",
    id: "optima-tripod-screen-84",
    brand: "Optima",
    name: "Optima Tripod Screen 84\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 84 Inch",
    ports: "213 cm x 213 cm",
    price: 850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-tripod-screen.jpg",
    id: "optima-tripod-screen-96",
    brand: "Optima",
    name: "Optima Tripod Screen 96\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 96 Inch",
    ports: "244 cm x 244 cm",
    price: 1200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-70",
    brand: "Optima",
    name: "Optima Motorized Screen 70\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 70 Inch",
    ports: "178 cm x 178 cm",
    price: 1600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-84",
    brand: "Optima",
    name: "Optima Motorized Screen 84\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 84 Inch",
    ports: "213 cm x 213 cm",
    price: 1900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-96",
    brand: "Optima",
    name: "Optima Motorized Screen 96\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 96 Inch",
    ports: "244 cm x 244 cm",
    price: 2200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-120",
    brand: "Optima",
    name: "Optima Motorized Screen 120\"",
    category: "Layar Proyektor",
    specLine: "Rasio 1:1 · 120 Inch",
    ports: "305 cm x 305 cm",
    price: 3100000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-wide-200",
    brand: "Optima",
    name: "Optima Motorized Screen Wide 200\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 200 Inch",
    ports: "400 cm x 300 cm",
    price: 8000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-tripod-screen-wide.jpg",
    id: "optima-tripod-screen-100",
    brand: "Optima",
    name: "Optima Tripod Screen 100\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 100 Inch",
    ports: "200 cm x 150 cm",
    price: 1900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-tripod-screen-wide.jpg",
    id: "optima-tripod-screen-120",
    brand: "Optima",
    name: "Optima Tripod Screen 120\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 120 Inch",
    ports: "244 cm x 183 cm",
    price: 2000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-tripod-screen-wide-150.jpg",
    id: "optima-tripod-screen-150",
    brand: "Optima",
    name: "Optima Tripod Screen 150\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 150 Inch",
    ports: "300 cm x 229 cm",
    price: 4700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-fast-fold-screen.jpg",
    id: "optima-fast-fold-screen-150",
    brand: "Optima",
    name: "Optima Fast Fold Screen 150\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 150 Inch",
    ports: "300 cm x 229 cm",
    price: 12900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-fast-fold-screen.jpg",
    id: "optima-fast-fold-screen-200",
    brand: "Optima",
    name: "Optima Fast Fold Screen 200\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 200 Inch",
    ports: "400 cm x 300 cm",
    price: 14900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-fast-fold-screen.jpg",
    id: "optima-fast-fold-screen-300",
    brand: "Optima",
    name: "Optima Fast Fold Screen 300\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 300 Inch",
    ports: "600 cm x 450 cm",
    price: 36900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-fix-frame-screen.jpg",
    id: "optima-fix-frame-screen-100",
    brand: "Optima",
    name: "Optima Fix Frame Screen 100\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 100 Inch",
    ports: "221 cm x 124 cm",
    price: 5600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-fix-frame-screen.jpg",
    id: "optima-fix-frame-screen-120",
    brand: "Optima",
    name: "Optima Fix Frame Screen 120\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 120 Inch",
    ports: "265 cm x 148 cm",
    price: 5700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-fix-frame-screen.jpg",
    id: "optima-fix-frame-screen-133",
    brand: "Optima",
    name: "Optima Fix Frame Screen 133\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 133 Inch",
    ports: "300 cm x 165 cm",
    price: 8000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-fix-frame-screen.jpg",
    id: "optima-fix-frame-screen-150",
    brand: "Optima",
    name: "Optima Fix Frame Screen 150\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 150 Inch",
    ports: "332 cm x 187 cm",
    price: 9200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-floor-up-screen.jpg",
    id: "optima-motorized-floor-up-screen-100",
    brand: "Optima",
    name: "Optima Motorized Floor Up Screen 100\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 100 Inch",
    ports: "221 cm x 124 cm",
    price: 17900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-floor-up-screen.jpg",
    id: "optima-motorized-floor-up-screen-120",
    brand: "Optima",
    name: "Optima Motorized Floor Up Screen 120\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 120 Inch",
    ports: "265 cm x 148 cm",
    price: 19900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-wide-100-43",
    brand: "Optima",
    name: "Optima Motorized Screen Wide 100 (4:3)\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 100 Inch",
    ports: "200 cm x 150 cm",
    price: 2700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-wide-120-43",
    brand: "Optima",
    name: "Optima Motorized Screen Wide 120 (4:3)\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 120 Inch",
    ports: "244 cm x 180 cm",
    price: 3000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-wide-150-43",
    brand: "Optima",
    name: "Optima Motorized Screen Wide 150 (4:3)\"",
    category: "Layar Proyektor",
    specLine: "Rasio 4:3 · 150 Inch",
    ports: "300 cm x 229 cm",
    price: 3500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-wide-100-169",
    brand: "Optima",
    name: "Optima Motorized Screen Wide 100 (16:9)\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 100 Inch",
    ports: "221 cm x 125 cm",
    price: 2900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-wide-120-169",
    brand: "Optima",
    name: "Optima Motorized Screen Wide 120 (16:9)\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 120 Inch",
    ports: "265 cm x 148 cm",
    price: 3300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-wide-133",
    brand: "Optima",
    name: "Optima Motorized Screen Wide 133\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 133 Inch",
    ports: "300 cm x 165 cm",
    price: 3500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/optima-motorized-screen.jpg",
    id: "optima-motorized-screen-wide-150-169",
    brand: "Optima",
    name: "Optima Motorized Screen Wide 150 (16:9)\"",
    category: "Layar Proyektor",
    specLine: "Rasio 16:9 · 150 Inch",
    ports: "332 cm x 187 cm",
    price: 6200000,
    priceIsEstimate: true,
    icon: "projector"
  },

  /* ====================================================================
     BATCH BARU — BREKET, MONITOR & MONITOR VIEWSONIC
     4 breket/meja tripod + 44 monitor dari
     PRODUCT_BREKET_DAN_MONITOR_WEBSITE.xlsx + 48 monitor ViewSonic dari
     VIEWSONIC_MONITOR.zip. Kategori baru "Aksesoris" dan "Monitor" —
     otomatis muncul di filter lewat buildDynamicFilters(), tidak perlu
     ubah HTML.
     7 monitor ViewSonic harganya "ASK" di pricelist (price: null) --
     kartu produknya otomatis tampil "Hubungi kami untuk harga" dengan
     tombol tanya-harga langsung ke WhatsApp, bukan tombol tambah keranjang.
     ==================================================================== */
  {
    image: "assets/img/breket-ceiling.jpg",
    id: "breket-ceiling",
    brand: "Non-Brand",
    name: "Breket Projektor Ceiling",
    category: "Aksesoris",
    specLine: "Ceiling Plafon Up To 80 cm",
    ports: "Max Beban 5 KG",
    price: 150000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/breket-ceiling-wall.jpg",
    id: "breket-ceiling-wall",
    brand: "Optima",
    name: "Optima Breket Projektor Ceiling / Wall",
    category: "Aksesoris",
    specLine: "Ceiling / Wall Up To 60 cm",
    ports: "Max Beban 7 KG",
    price: 250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/breket-motorized.jpg",
    id: "breket-motorized",
    brand: "Optima",
    name: "Optima Breket Projektor Motorized",
    category: "Aksesoris",
    specLine: "Ceiling Plafon Remote Up To 1,5 M",
    ports: "Max Beban 15 KG",
    price: 4000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/meja-tripod.jpg",
    id: "meja-tripod",
    brand: "Optima",
    name: "Optima Meja Tripod Projektor",
    category: "Aksesoris",
    specLine: "Tinggi Meja Up To 1 M",
    ports: "Cocok Untuk Semua Proyektor",
    price: 450000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-ed273u-p2.jpg",
    id: "mon-acer-ed273u-p2",
    brand: "Acer",
    name: "Acer ED273U_P2",
    category: "Monitor",
    specLine: "27 inch · VA Curved 1000R",
    ports: "HDMI | DP",
    price: 2300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-ek221qj0.jpg",
    id: "mon-acer-ek221qj0",
    brand: "Acer",
    name: "Acer EK221QJ0",
    category: "Monitor",
    specLine: "22 inch · VA",
    ports: "VGA | HDMI",
    price: 1250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-ek221qh3.jpg",
    id: "mon-acer-ek221qh3",
    brand: "Acer",
    name: "Acer EK221QH3",
    category: "Monitor",
    specLine: "22 inch · VA",
    ports: "VGA | HDMI",
    price: 1230000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-ek221qe3.jpg",
    id: "mon-acer-ek221qe3",
    brand: "Acer",
    name: "Acer EK221QE3",
    category: "Monitor",
    specLine: "22 inch · IPS",
    ports: "VGA | HDMI",
    price: 1250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-ek271g.jpg",
    id: "mon-acer-ek271g",
    brand: "Acer",
    name: "Acer EK271G",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "VGA | HDMI",
    price: 1700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-x34-v3.jpg",
    id: "mon-acer-x34-v3",
    brand: "Acer",
    name: "Acer X34 V3",
    category: "Monitor",
    specLine: "34 inch · Ultrawide Mini LED Curved",
    ports: "HDMI | DP | Type C",
    price: 13000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-sa243y.jpg",
    id: "mon-acer-sa243y",
    brand: "Acer",
    name: "Acer SA243Y",
    category: "Monitor",
    specLine: "24 inch · IPS",
    ports: "HDMI | VGA",
    price: 1560000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-pm161qj.jpg",
    id: "mon-acer-pm161qj",
    brand: "Acer",
    name: "Acer PM161QJ",
    category: "Monitor",
    specLine: "16 inch · Monitor Portable",
    ports: "Mini HDMI | USB C",
    price: 1950000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-pm161qt.jpg",
    id: "mon-acer-pm161qt",
    brand: "Acer",
    name: "Acer PM161QT",
    category: "Monitor",
    specLine: "16 inch · Monitor Touchscreen",
    ports: "Mini HDMI | USB C",
    price: 2500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-acer-16pd3q.jpg",
    id: "mon-acer-16pd3q",
    brand: "Acer",
    name: "Acer 16PD3Q",
    category: "Monitor",
    specLine: "16 inch · Dual Monitor Portable",
    ports: "Mini HDMI | USB C",
    price: 4900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-benq-gw2791.jpg",
    id: "mon-benq-gw2791",
    brand: "BenQ",
    name: "BenQ GW2791",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "HDMI | DP",
    price: 1800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-benq-ma270u-nano-matte.jpg",
    id: "mon-benq-ma270u-nano-matte",
    brand: "BenQ",
    name: "BenQ MA270U - Nano Matte",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "USB‑C (DP Alt | 90W PD) | HDMI×2 | USB‑A×2 | USB‑C downstream",
    price: 8850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-benq-ma320u-nano-matte.jpg",
    id: "mon-benq-ma320u-nano-matte",
    brand: "BenQ",
    name: "BenQ MA320U - Nano Matte",
    category: "Monitor",
    specLine: "32 inch · IPS",
    ports: "USB‑C (DP Alt | 90W PD) | HDMI×2 | USB‑A×2 | USB‑C downstream",
    price: 10700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-benq-ma270up-nano-glossy.jpg",
    id: "mon-benq-ma270up-nano-glossy",
    brand: "BenQ",
    name: "BenQ MA270UP - Nano Glossy",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "USB‑C (DP Alt | 90W PD) | HDMI×2 | USB‑A×2 | USB‑C downstream",
    price: 1600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-benq-ma320up-nano-glossy.jpg",
    id: "mon-benq-ma320up-nano-glossy",
    brand: "BenQ",
    name: "BenQ MA320UP - Nano Glossy",
    category: "Monitor",
    specLine: "32 inch · IPS",
    ports: "USB‑C (DP Alt | 90W PD) | HDMI×2 | USB‑A×2 | USB‑C downstream",
    price: 13200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-benq-ma270s-nano-glossy.jpg",
    id: "mon-benq-ma270s-nano-glossy",
    brand: "BenQ",
    name: "BenQ MA270S - Nano Glossy",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "HDMI 2.1×2 | Thunderbolt 4 96W×1 | Thunderbolt 4 Out×1 | USB-C×1",
    price: 20100000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-benq-pd2706u.jpg",
    id: "mon-benq-pd2706u",
    brand: "BenQ",
    name: "BenQ PD2706U",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "USB‑C (DP Alt | 90W PD) | HDMI×1 | DP×1 | USB hub | Hotkey Puck G2",
    price: 10850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-gigabyte-gs25f14.jpg",
    id: "mon-gigabyte-gs25f14",
    brand: "Gigabyte",
    name: "Gigabyte GS25F14",
    category: "Monitor",
    specLine: "25 inch · IPS",
    ports: "HDMI | DP",
    price: 1500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-gigabyte-gs27fa.jpg",
    id: "mon-gigabyte-gs27fa",
    brand: "Gigabyte",
    name: "Gigabyte GS27FA",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "HDMI | DP",
    price: 2000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-gigabyte-g27q20.jpg",
    id: "mon-gigabyte-g27q20",
    brand: "Gigabyte",
    name: "Gigabyte G27Q20",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "HDMI | DP",
    price: 2850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-gigabyte-g34wqc2.jpg",
    id: "mon-gigabyte-g34wqc2",
    brand: "Gigabyte",
    name: "Gigabyte G34WQC2",
    category: "Monitor",
    specLine: "34 inch · VA",
    ports: "HDMI | DP",
    price: 4200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-gigabyte-mo27q2.jpg",
    id: "mon-gigabyte-mo27q2",
    brand: "Gigabyte",
    name: "Gigabyte MO27Q2",
    category: "Monitor",
    specLine: "27 inch · OLED",
    ports: "HDMI | DP | Type C",
    price: 9850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-lg-27u411-b.jpg",
    id: "mon-lg-27u411-b",
    brand: "LG",
    name: "LG 27U411-B",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "HDMI | D-Sub",
    price: 1850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-lg-24g411a-b-ati.jpg",
    id: "mon-lg-24g411a-b-ati",
    brand: "LG",
    name: "LG 24G411A-B.ATI",
    category: "Monitor",
    specLine: "24 inch · IPS",
    ports: "HDMI | DP",
    price: 1650000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-lg-27g411a-b-ati.jpg",
    id: "mon-lg-27g411a-b-ati",
    brand: "LG",
    name: "LG 27G411A-B.ATI",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "HDMI | DP",
    price: 1950000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-lg-27g610a-b-atiq.jpg",
    id: "mon-lg-27g610a-b-atiq",
    brand: "LG",
    name: "LG 27G610A-B.ATIQ",
    category: "Monitor",
    specLine: "27 inch · IPS",
    ports: "HDMI | DP",
    price: 3000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-lg-34u511a-b-ati-div.jpg",
    id: "mon-lg-34u511a-b-ati-div",
    brand: "LG",
    name: "LG 34U511A-B.ATI-DIV",
    category: "Monitor",
    specLine: "34 inch · IPS",
    ports: "HDMI | DP",
    price: 3900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-enlight-en16p.jpg",
    id: "mon-enlight-en16p",
    brand: "Enlight",
    name: "Enlight EN16P",
    category: "Monitor",
    specLine: "16 inch · IPS 1920x1080 (FHD) 100Hz 5ms SPEAKER yes",
    ports: "Mini HDMI | Type-C Data | Typec-C PD | 3 | 5mm Jack",
    price: 1560000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-enlight-en19p.jpg",
    id: "mon-enlight-en19p",
    brand: "Enlight",
    name: "Enlight EN19P",
    category: "Monitor",
    specLine: "19 inch · IPS 1920x1080 (FHD) 100Hz 5ms SPEAKER yes",
    ports: "Mini HDMI | Type-C Data | Typec-C PD | 3 | 5mm Jack",
    price: 2340000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-enlight-en14d2.jpg",
    id: "mon-enlight-en14d2",
    brand: "Enlight",
    name: "Enlight EN14D2",
    category: "Monitor",
    specLine: "14 inchx2 (Right and Left side with Laptop Docking) · IPS 1920x1080 (FHD) 60Hz 5ms SPEAKER No",
    ports: "Type-C Data*2 | Type-C PD *1",
    price: 3600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-enlight-en19p2.jpg",
    id: "mon-enlight-en19p2",
    brand: "Enlight",
    name: "Enlight EN19P2",
    category: "Monitor",
    specLine: "19 inchx2 (Upper and Lower side's Display) · IPS 1920x1080 (FHD) 120Hz 5ms SPEAKER yes",
    ports: "Mini HDMI*2 | Type-C Data*2 | Type-C PD | 3.5 Jack Audio",
    price: 5600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-dahua-dhi-lm32-u400p.jpg",
    id: "mon-dahua-dhi-lm32-u400p",
    brand: "Dahua",
    name: "Dahua DHI-LM32-U400P",
    category: "Monitor",
    specLine: "32 inch · PANEL VA 3840×2160 (UHD) 60Hz 20ms SPEAKER 10W x 2",
    ports: "HDMI | Type C",
    price: 14800000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela5230eu-xiaomi-monitor-a22i.jpg",
    id: "mon-xiaomi-ela5230eu-xiaomi-monitor-a22i",
    brand: "Xiaomi",
    name: "Xiaomi ELA5230EU - Monitor A22i",
    category: "Monitor",
    specLine: "22 inch · PANEL VA 1920x1080 (FHD) 75Hz",
    ports: "HDMI | VGA",
    price: 1380000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela6416eu-xiaomi-monitor-a24i-2026.jpg",
    id: "mon-xiaomi-ela6416eu-xiaomi-monitor-a24i-2026",
    brand: "Xiaomi",
    name: "Xiaomi ELA6416EU - Monitor A24i 2026",
    category: "Monitor",
    specLine: "24 inch · IPS 1920x1080 (FHD) 144Hz 6ms",
    ports: "DP 1.4 | HDMI | DC IN",
    price: 1780000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela6410eu-xiaomi-monitor-a27i-2026.jpg",
    id: "mon-xiaomi-ela6410eu-xiaomi-monitor-a27i-2026",
    brand: "Xiaomi",
    name: "Xiaomi ELA6410EU - Monitor A27i 2026",
    category: "Monitor",
    specLine: "27 inch · IPS 1920x1080 (FHD) 144Hz 6ms",
    ports: "HDMI | DP",
    price: 2200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela6568eu-xiaomi-monitor-a27qi-2026.jpg",
    id: "mon-xiaomi-ela6568eu-xiaomi-monitor-a27qi-2026",
    brand: "Xiaomi",
    name: "Xiaomi ELA6568EU - Monitor A27Qi 2026",
    category: "Monitor",
    specLine: "27 inch · IPS 2560 x 1440 (2K) 120Hz 6ms",
    ports: "DP 1.4 | HDMI 2.0 | Audio | DC IN",
    price: 2780000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela6221eu-xiaomi-4k-monitor-a27ui.jpg",
    id: "mon-xiaomi-ela6221eu-xiaomi-4k-monitor-a27ui",
    brand: "Xiaomi",
    name: "Xiaomi ELA6221EU - 4K Monitor A27Ui",
    category: "Monitor",
    specLine: "27 inch · IPS 3840 x 2160 (4K) 60Hz 6ms",
    ports: "DP | USB2.0 | HDMI | Audio | USB-C | DC IN power port",
    price: 3850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela6364eu-xiaomi-gaming-monitor-g24i-2026.jpg",
    id: "mon-xiaomi-ela6364eu-xiaomi-gaming-monitor-g24i-2026",
    brand: "Xiaomi",
    name: "Xiaomi ELA6364EU - Gaming Monitor G24i 2026",
    category: "Monitor",
    specLine: "24 inch · IPS 1920x1080 (FHD) 200Hz 1ms",
    ports: "DP port | HDMI port 1 Audio port | DC IN",
    price: 2150000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela6734eu-xiaomi-monitor-g25i-2026-eu.jpg",
    id: "mon-xiaomi-ela6734eu-xiaomi-monitor-g25i-2026-eu",
    brand: "Xiaomi",
    name: "Xiaomi ELA6734EU - Monitor G25i 2026-EU",
    category: "Monitor",
    specLine: "25 inch · IPS 1920x1080 (FHD) - HDR400 240Hz 1ms",
    ports: "DP port | HDMI port 1 Audio port | DC IN",
    price: 2300000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela5375eu-xiaomi-gaming-monitor-g27i.jpg",
    id: "mon-xiaomi-ela5375eu-xiaomi-gaming-monitor-g27i",
    brand: "Xiaomi",
    name: "Xiaomi ELA5375EU - Gaming Monitor G27i",
    category: "Monitor",
    specLine: "27 inch · IPS 1920 × 1080 (FHD) 165Hz 1ms",
    ports: "HDMI | DP",
    price: 2100000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela6370eu-xiaomi-gaming-monitor-g27i-2026.jpg",
    id: "mon-xiaomi-ela6370eu-xiaomi-gaming-monitor-g27i-2026",
    brand: "Xiaomi",
    name: "Xiaomi ELA6370EU - Gaming Monitor G27i 2026",
    category: "Monitor",
    specLine: "27 inch · IPS 1920 × 1080 (FHD) 200Hz 1ms",
    ports: "DP port | HDMI port | Audio port | DC IN",
    price: 2780000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela5593eu-xiaomi-2k-gaming-monitor-g27qi.jpg",
    id: "mon-xiaomi-ela5593eu-xiaomi-2k-gaming-monitor-g27qi",
    brand: "Xiaomi",
    name: "Xiaomi ELA5593EU - 2K Gaming Monitor G27Qi",
    category: "Monitor",
    specLine: "27 inch · IPS 2560 x 1440 (2K) 180Hz 1ms",
    ports: "DP port | HDMI port | Audio port | DC IN",
    price: 2900000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela5585eu-xiaomi-mini-led-gaming-monitor-g-pro-27i.jpg",
    id: "mon-xiaomi-ela5585eu-xiaomi-mini-led-gaming-monitor-g-pro-27i",
    brand: "Xiaomi",
    name: "Xiaomi ELA5585EU - Mini LED Gaming Monitor G Pro 27i",
    category: "Monitor",
    specLine: "27 inch · IPS 2560 x 1440 (QHD) 180Hz 1ms",
    ports: "DP 1.4 x 2 HDMI 2.0 x 2 Audio x 1 DC jack x 1",
    price: 4650000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-xiaomi-ela6562eu-xiaomi-curved-gaming-monitor-g34wqi-2026.jpg",
    id: "mon-xiaomi-ela6562eu-xiaomi-curved-gaming-monitor-g34wqi-2026",
    brand: "Xiaomi",
    name: "Xiaomi ELA6562EU - Curved Gaming Monitor G34WQi 2026",
    category: "Monitor",
    specLine: "34 inch · PANEL VA 3440 x 1440 (WQHD) - HDR400 180Hz 1ms",
    ports: "DP port | HDMI port | Audio port | DC IN",
    price: 5200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-td1630-3.jpg",
    id: "mon-viewsonic-td1630-3",
    brand: "ViewSonic",
    name: "ViewSonic TD1630-3",
    category: "Monitor",
    specLine: "15.6 inch · TN · WXGA (1366x768) · 60Hz",
    ports: "VGA | HDMI",
    price: 3200000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-td1655-incl-passive-touch-pen.jpg",
    id: "mon-viewsonic-td1655-incl-passive-touch-pen",
    brand: "ViewSonic",
    name: "ViewSonic TD1655 incl passive touch pen",
    category: "Monitor",
    specLine: "15.6 inch · IPS · FHD (1920x1080) · 60Hz",
    ports: "Mini HDMI | USB Type C",
    price: 3950000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-td2223-2.jpg",
    id: "mon-viewsonic-td2223-2",
    brand: "ViewSonic",
    name: "ViewSonic TD2223-2",
    category: "Monitor",
    specLine: "22 inch · VA · FHD (1920x1080) · 75Hz",
    ports: "VGA | HDMI | DVI-D",
    price: 3380000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-td2423.jpg",
    id: "mon-viewsonic-td2423",
    brand: "ViewSonic",
    name: "ViewSonic TD2423",
    category: "Monitor",
    specLine: "24 inch · VA · FHD (1920x1080) · 75Hz",
    ports: "VGA | HDMI | USB Type A | B | DVI-D",
    price: 3530000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-td2455-incl-passive-touch-pen.jpg",
    id: "mon-viewsonic-td2455-incl-passive-touch-pen",
    brand: "ViewSonic",
    name: "ViewSonic TD2455 incl passive touch pen",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 60Hz",
    ports: "HDMI | DP | USB Type A | B | C",
    price: null,
    priceIsEstimate: false,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-td2465.jpg",
    id: "mon-viewsonic-td2465",
    brand: "ViewSonic",
    name: "ViewSonic TD2465",
    category: "Monitor",
    specLine: "24 inch · VA · FHD (1920x1080) · 60Hz",
    ports: "VGA | HDMI | USB Type A | B | DP",
    price: null,
    priceIsEstimate: false,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-td2760.jpg",
    id: "mon-viewsonic-td2760",
    brand: "ViewSonic",
    name: "ViewSonic TD2760",
    category: "Monitor",
    specLine: "27 inch · VA · FHD (1920x1080) · 60Hz",
    ports: "HDMI | DP | VGA",
    price: 7000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va1650.jpg",
    id: "mon-viewsonic-va1650",
    brand: "ViewSonic",
    name: "ViewSonic VA1650",
    category: "Monitor",
    specLine: "16 inch · IPS · FHD (1920x1080) · 60Hz",
    ports: "HDMI | USB C",
    price: 1600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va22e2-h.jpg",
    id: "mon-viewsonic-va22e2-h",
    brand: "ViewSonic",
    name: "ViewSonic VA22E2-H",
    category: "Monitor",
    specLine: "22 inch · VA · FHD (1920x1080) · 100Hz",
    ports: "VGA | HDMI",
    price: 895000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va221a-h.jpg",
    id: "mon-viewsonic-va221a-h",
    brand: "ViewSonic",
    name: "ViewSonic VA221A-H",
    category: "Monitor",
    specLine: "22 inch · IPS · FHD (1920x1080) · 120Hz",
    ports: "VGA | HDMI",
    price: 1055000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va240a-h.jpg",
    id: "mon-viewsonic-va240a-h",
    brand: "ViewSonic",
    name: "ViewSonic VA240A-H",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 120Hz",
    ports: "VGA | HDMI",
    price: null,
    priceIsEstimate: false,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va24g1-h.jpg",
    id: "mon-viewsonic-va24g1-h",
    brand: "ViewSonic",
    name: "ViewSonic VA24G1-H",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 144Hz",
    ports: "VGA | HDMI",
    price: 1145000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va24g2-h.jpg",
    id: "mon-viewsonic-va24g2-h",
    brand: "ViewSonic",
    name: "ViewSonic VA24G2-H",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 144Hz",
    ports: "VGA | HDMI",
    price: null,
    priceIsEstimate: false,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va2432-h-2.jpg",
    id: "mon-viewsonic-va2432-h-2",
    brand: "ViewSonic",
    name: "ViewSonic VA2432-H-2",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 100Hz",
    ports: "VGA | HDMI",
    price: 1100000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va2432a-h.jpg",
    id: "mon-viewsonic-va2432a-h",
    brand: "ViewSonic",
    name: "ViewSonic VA2432A-H",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 120Hz",
    ports: "VGA | HDMI",
    price: 1150000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va2432-h-w-2.jpg",
    id: "mon-viewsonic-va2432-h-w-2",
    brand: "ViewSonic",
    name: "ViewSonic VA2432-H-W-2",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 100Hz",
    ports: "VGA | HDMI",
    price: 1320000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va2436-h-pn.jpg",
    id: "mon-viewsonic-va2436-h-pn",
    brand: "ViewSonic",
    name: "ViewSonic VA2436-H-PN",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 100Hz",
    ports: "VGA | HDMI",
    price: null,
    priceIsEstimate: false,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va2732-h-2.jpg",
    id: "mon-viewsonic-va2732-h-2",
    brand: "ViewSonic",
    name: "ViewSonic VA2732-H-2",
    category: "Monitor",
    specLine: "27 inch · IPS · FHD (1920x1080) · 100Hz",
    ports: "VGA | HDMI",
    price: 1530000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va2732-h-w.jpg",
    id: "mon-viewsonic-va2732-h-w",
    brand: "ViewSonic",
    name: "ViewSonic VA2732-H-W",
    category: "Monitor",
    specLine: "27 inch · IPS · FHD (1920x1080) · 100Hz",
    ports: "VGA | HDMI",
    price: 1500000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va3208-4k-mhd.jpg",
    id: "mon-viewsonic-va3208-4k-mhd",
    brand: "ViewSonic",
    name: "ViewSonic VA3208-4K-MHD",
    category: "Monitor",
    specLine: "32 inch · VA · UHD (3840x2160) · 60Hz",
    ports: "HDMI | DP",
    price: 3850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-va3209-mh.jpg",
    id: "mon-viewsonic-va3209-mh",
    brand: "ViewSonic",
    name: "ViewSonic VA3209-MH",
    category: "Monitor",
    specLine: "32 inch · IPS · FHD (1920x1080) · 75Hz",
    ports: "VGA | HDMI",
    price: 2480000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vg2408.jpg",
    id: "mon-viewsonic-vg2408",
    brand: "ViewSonic",
    name: "ViewSonic VG2408",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 100Hz",
    ports: "HDMI | DP | USB Type A | C",
    price: 1735000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vg2441v-with-webcam.jpg",
    id: "mon-viewsonic-vg2441v-with-webcam",
    brand: "ViewSonic",
    name: "ViewSonic VG2441V with Webcam",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 120Hz",
    ports: "HDMI | DP | USB Type A & C",
    price: 3000000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vg3820c.jpg",
    id: "mon-viewsonic-vg3820c",
    brand: "ViewSonic",
    name: "ViewSonic VG3820C",
    category: "Monitor",
    specLine: "38 inch Curved · IPS · WQHD (3840x1600) · 75Hz",
    ports: "HDMI | DP | USB Type A | B | C",
    price: null,
    priceIsEstimate: false,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vp16-oled.jpg",
    id: "mon-viewsonic-vp16-oled",
    brand: "ViewSonic",
    name: "ViewSonic VP16-OLED",
    category: "Monitor",
    specLine: "16 inch · OLED · FHD (1920x1080) · 60Hz",
    ports: "USB type C | Micro HDMI",
    price: 6425000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vp2456a.jpg",
    id: "mon-viewsonic-vp2456a",
    brand: "ViewSonic",
    name: "ViewSonic VP2456A",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 120Hz",
    ports: "HDMI | DP | USB Type A | C",
    price: 3420000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vp2756a-2k.jpg",
    id: "mon-viewsonic-vp2756a-2k",
    brand: "ViewSonic",
    name: "ViewSonic VP2756A-2K",
    category: "Monitor",
    specLine: "27 inch · IPS · QHD (2560x1440) · 120Hz",
    ports: "HDMI | DP | USB Type C | Type A x3",
    price: 4720000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vp2756-4k.jpg",
    id: "mon-viewsonic-vp2756-4k",
    brand: "ViewSonic",
    name: "ViewSonic VP2756-4K",
    category: "Monitor",
    specLine: "27 inch · IPS · UHD (3840x2160) · 60Hz",
    ports: "HDMI | DP | USB Type C",
    price: 6600000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vp2766-2k.jpg",
    id: "mon-viewsonic-vp2766-2k",
    brand: "ViewSonic",
    name: "ViewSonic VP2766-2K",
    category: "Monitor",
    specLine: "27 inch · IPS · QHD (2560x1440) · 120Hz",
    ports: "HDMI | USB Type A & C",
    price: 4750000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vp2766-2k-w.jpg",
    id: "mon-viewsonic-vp2766-2k-w",
    brand: "ViewSonic",
    name: "ViewSonic VP2766-2K-W",
    category: "Monitor",
    specLine: "27 inch · IPS · QHD (2560x1440) · 120Hz",
    ports: "HDMI | USB Type A & C",
    price: 5050000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vp2776.jpg",
    id: "mon-viewsonic-vp2776",
    brand: "ViewSonic",
    name: "ViewSonic VP2776",
    category: "Monitor",
    specLine: "27 inch · IPS · QHD (2560x1440) · 165Hz",
    ports: "HDMI | DP | USB Type A | B | C",
    price: null,
    priceIsEstimate: false,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx2425.jpg",
    id: "mon-viewsonic-vx2425",
    brand: "ViewSonic",
    name: "ViewSonic VX2425",
    category: "Monitor",
    specLine: "24 inch · VA · FHD (1920x1080) · 200Hz",
    ports: "HDMI | DP",
    price: 1425000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx2428aj-bl.jpg",
    id: "mon-viewsonic-vx2428aj-bl",
    brand: "ViewSonic",
    name: "ViewSonic VX2428AJ-BL",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 240Hz",
    ports: "HDMI | DP",
    price: 2250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx2428aj-pk.jpg",
    id: "mon-viewsonic-vx2428aj-pk",
    brand: "ViewSonic",
    name: "ViewSonic VX2428AJ-PK",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 240Hz",
    ports: "HDMI | DP",
    price: 2250000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx2479-hd-pro.jpg",
    id: "mon-viewsonic-vx2479-hd-pro",
    brand: "ViewSonic",
    name: "ViewSonic VX2479-HD-PRO",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 180Hz",
    ports: "HDMI | DP",
    price: 1440000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx2479a-hd-pro.jpg",
    id: "mon-viewsonic-vx2479a-hd-pro",
    brand: "ViewSonic",
    name: "ViewSonic VX2479A-HD-PRO",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 240Hz",
    ports: "HDMI | DP",
    price: 1480000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx2532.jpg",
    id: "mon-viewsonic-vx2532",
    brand: "ViewSonic",
    name: "ViewSonic VX2532",
    category: "Monitor",
    specLine: "25 inch · IPS · FHD (1920x1080) · 320Hz",
    ports: "HDMI | DP",
    price: 2440000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx27g32a-2k.jpg",
    id: "mon-viewsonic-vx27g32a-2k",
    brand: "ViewSonic",
    name: "ViewSonic VX27G32A-2K",
    category: "Monitor",
    specLine: "27 inch · IPS · QHD (2560x1440) · 275Hz",
    ports: "HDMI | DP",
    price: 3280000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx27g33-2k.jpg",
    id: "mon-viewsonic-vx27g33-2k",
    brand: "ViewSonic",
    name: "ViewSonic VX27G33-2K",
    category: "Monitor",
    specLine: "27 inch · IPS · QHD (2560x1440) · 340Hz",
    ports: "HDMI | DP",
    price: 3780000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx2779a-hd-pro.jpg",
    id: "mon-viewsonic-vx2779a-hd-pro",
    brand: "ViewSonic",
    name: "ViewSonic VX2779A-HD-PRO",
    category: "Monitor",
    specLine: "27 inch · IPS · FHD (1920x1080) · 240Hz",
    ports: "HDMI | DP",
    price: 1850000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx3218c-2k.jpg",
    id: "mon-viewsonic-vx3218c-2k",
    brand: "ViewSonic",
    name: "ViewSonic VX3218C-2K",
    category: "Monitor",
    specLine: "32 inch · VA · QHD (2560x1440) · 180Hz",
    ports: "HDMI | DP",
    price: 3700000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx3276-mhd-3.jpg",
    id: "mon-viewsonic-vx3276-mhd-3",
    brand: "ViewSonic",
    name: "ViewSonic VX3276-MHD-3",
    category: "Monitor",
    specLine: "32 inch · IPS · FHD (1920x1080) · 75Hz",
    ports: "HDMI | DP",
    price: 2830000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-vx3276-2k-mhd-2.jpg",
    id: "mon-viewsonic-vx3276-2k-mhd-2",
    brand: "ViewSonic",
    name: "ViewSonic VX3276-2K-MHD-2",
    category: "Monitor",
    specLine: "32 inch · IPS · QHD (2560x1440) · 75Hz",
    ports: "HDMI | DP | Mini DP",
    price: 3450000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-xg2409a.jpg",
    id: "mon-viewsonic-xg2409a",
    brand: "ViewSonic",
    name: "ViewSonic XG2409A",
    category: "Monitor",
    specLine: "24 inch · IPS · FHD (1920x1080) · 240Hz",
    ports: "HDMI | DP",
    price: 1950000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-xg2536.jpg",
    id: "mon-viewsonic-xg2536",
    brand: "ViewSonic",
    name: "ViewSonic XG2536",
    category: "Monitor",
    specLine: "25 inch · IPS · FHD (1920x1080) · 280Hz",
    ports: "HDMI 2x | DP",
    price: 3630000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-xg2709.jpg",
    id: "mon-viewsonic-xg2709",
    brand: "ViewSonic",
    name: "ViewSonic XG2709",
    category: "Monitor",
    specLine: "27 inch · IPS · FHD (1920x1080) · 180Hz",
    ports: "HDMI | DP",
    price: 2040000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-xg272-2k-oled.jpg",
    id: "mon-viewsonic-xg272-2k-oled",
    brand: "ViewSonic",
    name: "ViewSonic XG272-2K-OLED",
    category: "Monitor",
    specLine: "27 inch · OLED · QHD (2560x1440) · 240Hz",
    ports: "HDMI | DP",
    price: 12650000,
    priceIsEstimate: true,
    icon: "projector"
  },
  {
    image: "assets/img/mon-viewsonic-xg275d1-4k.jpg",
    id: "mon-viewsonic-xg275d1-4k",
    brand: "ViewSonic",
    name: "ViewSonic XG275D1-4K",
    category: "Monitor",
    specLine: "27 inch · IPS · UHD (3840x2160) · 160Hz",
    ports: "HDMI | DP | TypeC",
    price: 6100000,
    priceIsEstimate: true,
    icon: "projector"
  }
];
